package problema.pkg2.cliente;

/**
 *
 * @author leonardo
 */
public class Grid extends javax.swing.JPanel {
    javax.swing.JButton array[][]; 
    /**
     * Creates new form Grid
     */
    public Grid() {
        initComponents();
        this.setSize(436,436);
        array = new javax.swing.JButton[11][11];
        initArray();
    }
    private void initArray(){
        final int c = 30,s = 40; //constante de posição [x,y] e do tamanho de cada jButton [w,h]
        for (int i = 1; i <= 10; i++) {
            for (int j = 1; j <= 10; j++) {
                /*
                 * retorna os componentes em relação a suas posições x e y
                 * considerando que o primeiro está na posição ['c','c']
                 * e cada componente possui o tamanho ['s','s']
                 * estas constantes são utilizadas no cálcudo de posição
                 */
                array[i][j] = (javax.swing.JButton) this.getComponentAt((c+(j-1)*s),(c+(i-1)*s));
            }
        }
    }
    
    public final void controlField(boolean tof){
        for (int i = 1; i <= 10; i++) {
            for (int j = 1; j <= 10; j++) {
                array[i][j].setEnabled(tof);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(436, 436));
        setLayout(null);

        jLabel1.setText("A");
        add(jLabel1);
        jLabel1.setBounds(10, 40, 20, 20);

        jLabel2.setText("B");
        add(jLabel2);
        jLabel2.setBounds(10, 80, 20, 20);

        jLabel3.setText("C");
        add(jLabel3);
        jLabel3.setBounds(10, 120, 20, 20);

        jLabel4.setText("D");
        add(jLabel4);
        jLabel4.setBounds(10, 160, 20, 20);

        jLabel5.setText("E");
        add(jLabel5);
        jLabel5.setBounds(10, 200, 20, 20);

        jLabel6.setText("F");
        add(jLabel6);
        jLabel6.setBounds(10, 240, 20, 20);

        jLabel7.setText("G");
        add(jLabel7);
        jLabel7.setBounds(10, 280, 20, 20);

        jLabel8.setText("H");
        add(jLabel8);
        jLabel8.setBounds(10, 320, 20, 20);

        jLabel9.setText("I");
        add(jLabel9);
        jLabel9.setBounds(10, 360, 20, 20);

        jLabel10.setText("J");
        add(jLabel10);
        jLabel10.setBounds(10, 400, 20, 20);

        jLabel11.setText("1");
        add(jLabel11);
        jLabel11.setBounds(50, 10, 20, 15);

        jLabel12.setText("2");
        add(jLabel12);
        jLabel12.setBounds(90, 10, 20, 15);

        jLabel13.setText("3");
        add(jLabel13);
        jLabel13.setBounds(130, 10, 20, 15);

        jLabel14.setText("4");
        add(jLabel14);
        jLabel14.setBounds(170, 10, 20, 15);

        jLabel15.setText("5");
        add(jLabel15);
        jLabel15.setBounds(210, 10, 20, 15);

        jLabel16.setText("6");
        add(jLabel16);
        jLabel16.setBounds(250, 10, 20, 15);

        jLabel17.setText("7");
        add(jLabel17);
        jLabel17.setBounds(290, 10, 20, 15);

        jLabel18.setText("8");
        add(jLabel18);
        jLabel18.setBounds(330, 10, 20, 15);

        jLabel19.setText("9");
        add(jLabel19);
        jLabel19.setBounds(370, 10, 20, 15);

        jLabel20.setText(" 10");
        add(jLabel20);
        jLabel20.setBounds(400, 10, 30, 15);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton1);
        jButton1.setBounds(30, 30, 40, 40);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton2);
        jButton2.setBounds(70, 30, 40, 40);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton3);
        jButton3.setBounds(110, 30, 40, 40);

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton4);
        jButton4.setBounds(150, 30, 40, 40);

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton5);
        jButton5.setBounds(190, 30, 40, 40);

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton6.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton6);
        jButton6.setBounds(230, 30, 40, 40);

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton7.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton7);
        jButton7.setBounds(270, 30, 40, 40);

        jButton8.setBackground(new java.awt.Color(51, 51, 255));
        jButton8.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton8.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton8.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton8);
        jButton8.setBounds(310, 30, 40, 40);

        jButton9.setBackground(new java.awt.Color(51, 51, 255));
        jButton9.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton9.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton9.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton9);
        jButton9.setBounds(350, 30, 40, 40);

        jButton10.setBackground(new java.awt.Color(51, 51, 255));
        jButton10.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton10.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton10.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton10);
        jButton10.setBounds(390, 30, 40, 40);

        jButton11.setBackground(new java.awt.Color(51, 51, 255));
        jButton11.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton11.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton11.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton11);
        jButton11.setBounds(30, 70, 40, 40);

        jButton12.setBackground(new java.awt.Color(51, 51, 255));
        jButton12.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton12.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton12.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton12);
        jButton12.setBounds(70, 70, 40, 40);

        jButton13.setBackground(new java.awt.Color(51, 51, 255));
        jButton13.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton13.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton13.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton13);
        jButton13.setBounds(110, 70, 40, 40);

        jButton14.setBackground(new java.awt.Color(51, 51, 255));
        jButton14.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton14.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton14.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton14);
        jButton14.setBounds(150, 70, 40, 40);

        jButton15.setBackground(new java.awt.Color(51, 51, 255));
        jButton15.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton15.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton15.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton15);
        jButton15.setBounds(190, 70, 40, 40);

        jButton16.setBackground(new java.awt.Color(51, 51, 255));
        jButton16.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton16.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton16.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton16);
        jButton16.setBounds(230, 70, 40, 40);

        jButton17.setBackground(new java.awt.Color(51, 51, 255));
        jButton17.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton17.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton17.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton17);
        jButton17.setBounds(270, 70, 40, 40);

        jButton18.setBackground(new java.awt.Color(51, 51, 255));
        jButton18.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton18.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton18.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton18);
        jButton18.setBounds(310, 70, 40, 40);

        jButton19.setBackground(new java.awt.Color(51, 51, 255));
        jButton19.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton19.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton19.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton19);
        jButton19.setBounds(350, 70, 40, 40);

        jButton20.setBackground(new java.awt.Color(51, 51, 255));
        jButton20.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton20.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton20.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton20);
        jButton20.setBounds(390, 70, 40, 40);

        jButton21.setBackground(new java.awt.Color(51, 51, 255));
        jButton21.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton21.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton21.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton21);
        jButton21.setBounds(30, 110, 40, 40);

        jButton22.setBackground(new java.awt.Color(51, 51, 255));
        jButton22.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton22.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton22.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton22);
        jButton22.setBounds(70, 110, 40, 40);

        jButton23.setBackground(new java.awt.Color(51, 51, 255));
        jButton23.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton23.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton23.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton23);
        jButton23.setBounds(110, 110, 40, 40);

        jButton24.setBackground(new java.awt.Color(51, 51, 255));
        jButton24.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton24.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton24.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton24);
        jButton24.setBounds(150, 110, 40, 40);

        jButton25.setBackground(new java.awt.Color(51, 51, 255));
        jButton25.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton25.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton25.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton25);
        jButton25.setBounds(190, 110, 40, 40);

        jButton26.setBackground(new java.awt.Color(51, 51, 255));
        jButton26.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton26.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton26.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton26);
        jButton26.setBounds(230, 110, 40, 40);

        jButton27.setBackground(new java.awt.Color(51, 51, 255));
        jButton27.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton27.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton27.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton27);
        jButton27.setBounds(270, 110, 40, 40);

        jButton28.setBackground(new java.awt.Color(51, 51, 255));
        jButton28.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton28.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton28.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton28);
        jButton28.setBounds(310, 110, 40, 40);

        jButton29.setBackground(new java.awt.Color(51, 51, 255));
        jButton29.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton29.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton29.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton29);
        jButton29.setBounds(350, 110, 40, 40);

        jButton30.setBackground(new java.awt.Color(51, 51, 255));
        jButton30.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton30.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton30.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton30);
        jButton30.setBounds(390, 110, 40, 40);

        jButton31.setBackground(new java.awt.Color(51, 51, 255));
        jButton31.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton31.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton31.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton31);
        jButton31.setBounds(30, 150, 40, 40);

        jButton32.setBackground(new java.awt.Color(51, 51, 255));
        jButton32.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton32.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton32.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton32);
        jButton32.setBounds(70, 150, 40, 40);

        jButton33.setBackground(new java.awt.Color(51, 51, 255));
        jButton33.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton33.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton33.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton33);
        jButton33.setBounds(110, 150, 40, 40);

        jButton34.setBackground(new java.awt.Color(51, 51, 255));
        jButton34.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton34.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton34.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton34);
        jButton34.setBounds(150, 150, 40, 40);

        jButton35.setBackground(new java.awt.Color(51, 51, 255));
        jButton35.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton35.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton35.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton35);
        jButton35.setBounds(190, 150, 40, 40);

        jButton36.setBackground(new java.awt.Color(51, 51, 255));
        jButton36.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton36.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton36.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton36);
        jButton36.setBounds(230, 150, 40, 40);

        jButton37.setBackground(new java.awt.Color(51, 51, 255));
        jButton37.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton37.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton37.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton37);
        jButton37.setBounds(270, 150, 40, 40);

        jButton38.setBackground(new java.awt.Color(51, 51, 255));
        jButton38.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton38.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton38.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton38);
        jButton38.setBounds(310, 150, 40, 40);

        jButton39.setBackground(new java.awt.Color(51, 51, 255));
        jButton39.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton39.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton39.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton39);
        jButton39.setBounds(350, 150, 40, 40);

        jButton40.setBackground(new java.awt.Color(51, 51, 255));
        jButton40.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton40.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton40.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton40);
        jButton40.setBounds(390, 150, 40, 40);

        jButton41.setBackground(new java.awt.Color(51, 51, 255));
        jButton41.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton41.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton41.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton41);
        jButton41.setBounds(30, 190, 40, 40);

        jButton42.setBackground(new java.awt.Color(51, 51, 255));
        jButton42.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton42.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton42.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton42);
        jButton42.setBounds(70, 190, 40, 40);

        jButton43.setBackground(new java.awt.Color(51, 51, 255));
        jButton43.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton43.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton43.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton43);
        jButton43.setBounds(110, 190, 40, 40);

        jButton44.setBackground(new java.awt.Color(51, 51, 255));
        jButton44.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton44.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton44.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton44);
        jButton44.setBounds(150, 190, 40, 40);

        jButton45.setBackground(new java.awt.Color(51, 51, 255));
        jButton45.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton45.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton45.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton45);
        jButton45.setBounds(190, 190, 40, 40);

        jButton46.setBackground(new java.awt.Color(51, 51, 255));
        jButton46.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton46.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton46.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton46);
        jButton46.setBounds(230, 190, 40, 40);

        jButton47.setBackground(new java.awt.Color(51, 51, 255));
        jButton47.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton47.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton47.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton47);
        jButton47.setBounds(270, 190, 40, 40);

        jButton48.setBackground(new java.awt.Color(51, 51, 255));
        jButton48.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton48.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton48.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton48);
        jButton48.setBounds(310, 190, 40, 40);

        jButton49.setBackground(new java.awt.Color(51, 51, 255));
        jButton49.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton49.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton49.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton49);
        jButton49.setBounds(350, 190, 40, 40);

        jButton50.setBackground(new java.awt.Color(51, 51, 255));
        jButton50.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton50.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton50.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton50);
        jButton50.setBounds(390, 190, 40, 40);

        jButton51.setBackground(new java.awt.Color(51, 51, 255));
        jButton51.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton51.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton51.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton51);
        jButton51.setBounds(30, 230, 40, 40);

        jButton52.setBackground(new java.awt.Color(51, 51, 255));
        jButton52.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton52.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton52.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton52);
        jButton52.setBounds(70, 230, 40, 40);

        jButton53.setBackground(new java.awt.Color(51, 51, 255));
        jButton53.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton53.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton53.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton53);
        jButton53.setBounds(110, 230, 40, 40);

        jButton54.setBackground(new java.awt.Color(51, 51, 255));
        jButton54.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton54.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton54.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton54);
        jButton54.setBounds(150, 230, 40, 40);

        jButton55.setBackground(new java.awt.Color(51, 51, 255));
        jButton55.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton55.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton55.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton55);
        jButton55.setBounds(190, 230, 40, 40);

        jButton56.setBackground(new java.awt.Color(51, 51, 255));
        jButton56.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton56.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton56.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton56);
        jButton56.setBounds(230, 230, 40, 40);

        jButton57.setBackground(new java.awt.Color(51, 51, 255));
        jButton57.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton57.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton57.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton57);
        jButton57.setBounds(270, 230, 40, 40);

        jButton58.setBackground(new java.awt.Color(51, 51, 255));
        jButton58.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton58.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton58.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton58);
        jButton58.setBounds(310, 230, 40, 40);

        jButton59.setBackground(new java.awt.Color(51, 51, 255));
        jButton59.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton59.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton59.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton59);
        jButton59.setBounds(350, 230, 40, 40);

        jButton60.setBackground(new java.awt.Color(51, 51, 255));
        jButton60.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton60.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton60.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton60);
        jButton60.setBounds(390, 230, 40, 40);

        jButton61.setBackground(new java.awt.Color(51, 51, 255));
        jButton61.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton61.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton61.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton61);
        jButton61.setBounds(30, 270, 40, 40);

        jButton62.setBackground(new java.awt.Color(51, 51, 255));
        jButton62.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton62.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton62.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton62);
        jButton62.setBounds(70, 270, 40, 40);

        jButton63.setBackground(new java.awt.Color(51, 51, 255));
        jButton63.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton63.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton63.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton63);
        jButton63.setBounds(110, 270, 40, 40);

        jButton64.setBackground(new java.awt.Color(51, 51, 255));
        jButton64.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton64.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton64.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton64);
        jButton64.setBounds(150, 270, 40, 40);

        jButton65.setBackground(new java.awt.Color(51, 51, 255));
        jButton65.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton65.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton65.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton65);
        jButton65.setBounds(190, 270, 40, 40);

        jButton66.setBackground(new java.awt.Color(51, 51, 255));
        jButton66.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton66.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton66.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton66);
        jButton66.setBounds(230, 270, 40, 40);

        jButton67.setBackground(new java.awt.Color(51, 51, 255));
        jButton67.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton67.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton67.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton67);
        jButton67.setBounds(270, 270, 40, 40);

        jButton68.setBackground(new java.awt.Color(51, 51, 255));
        jButton68.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton68.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton68.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton68);
        jButton68.setBounds(310, 270, 40, 40);

        jButton69.setBackground(new java.awt.Color(51, 51, 255));
        jButton69.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton69.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton69.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton69);
        jButton69.setBounds(350, 270, 40, 40);

        jButton70.setBackground(new java.awt.Color(51, 51, 255));
        jButton70.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton70.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton70.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton70);
        jButton70.setBounds(390, 270, 40, 40);

        jButton71.setBackground(new java.awt.Color(51, 51, 255));
        jButton71.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton71.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton71.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton71);
        jButton71.setBounds(30, 310, 40, 40);

        jButton72.setBackground(new java.awt.Color(51, 51, 255));
        jButton72.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton72.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton72.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton72);
        jButton72.setBounds(70, 310, 40, 40);

        jButton73.setBackground(new java.awt.Color(51, 51, 255));
        jButton73.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton73.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton73.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton73);
        jButton73.setBounds(110, 310, 40, 40);

        jButton74.setBackground(new java.awt.Color(51, 51, 255));
        jButton74.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton74.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton74.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton74);
        jButton74.setBounds(150, 310, 40, 40);

        jButton75.setBackground(new java.awt.Color(51, 51, 255));
        jButton75.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton75.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton75.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton75);
        jButton75.setBounds(190, 310, 40, 40);

        jButton76.setBackground(new java.awt.Color(51, 51, 255));
        jButton76.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton76.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton76.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton76);
        jButton76.setBounds(230, 310, 40, 40);

        jButton77.setBackground(new java.awt.Color(51, 51, 255));
        jButton77.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton77.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton77.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton77);
        jButton77.setBounds(270, 310, 40, 40);

        jButton78.setBackground(new java.awt.Color(51, 51, 255));
        jButton78.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton78.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton78.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton78);
        jButton78.setBounds(310, 310, 40, 40);

        jButton79.setBackground(new java.awt.Color(51, 51, 255));
        jButton79.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton79.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton79.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton79);
        jButton79.setBounds(350, 310, 40, 40);

        jButton80.setBackground(new java.awt.Color(51, 51, 255));
        jButton80.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton80.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton80.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton80);
        jButton80.setBounds(390, 310, 40, 40);

        jButton81.setBackground(new java.awt.Color(51, 51, 255));
        jButton81.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton81.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton81.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton81);
        jButton81.setBounds(30, 350, 40, 40);

        jButton82.setBackground(new java.awt.Color(51, 51, 255));
        jButton82.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton82.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton82.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton82);
        jButton82.setBounds(70, 350, 40, 40);

        jButton83.setBackground(new java.awt.Color(51, 51, 255));
        jButton83.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton83.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton83.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton83);
        jButton83.setBounds(110, 350, 40, 40);

        jButton84.setBackground(new java.awt.Color(51, 51, 255));
        jButton84.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton84.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton84.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton84);
        jButton84.setBounds(150, 350, 40, 40);

        jButton85.setBackground(new java.awt.Color(51, 51, 255));
        jButton85.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton85.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton85.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton85);
        jButton85.setBounds(190, 350, 40, 40);

        jButton86.setBackground(new java.awt.Color(51, 51, 255));
        jButton86.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton86.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton86.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton86);
        jButton86.setBounds(230, 350, 40, 40);

        jButton87.setBackground(new java.awt.Color(51, 51, 255));
        jButton87.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton87.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton87.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton87);
        jButton87.setBounds(270, 350, 40, 40);

        jButton88.setBackground(new java.awt.Color(51, 51, 255));
        jButton88.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton88.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton88.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton88);
        jButton88.setBounds(310, 350, 40, 40);

        jButton89.setBackground(new java.awt.Color(51, 51, 255));
        jButton89.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton89.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton89.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton89);
        jButton89.setBounds(350, 350, 40, 40);

        jButton90.setBackground(new java.awt.Color(51, 51, 255));
        jButton90.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton90.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton90.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton90);
        jButton90.setBounds(390, 350, 40, 40);

        jButton91.setBackground(new java.awt.Color(51, 51, 255));
        jButton91.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton91.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton91.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton91);
        jButton91.setBounds(30, 390, 40, 40);

        jButton92.setBackground(new java.awt.Color(51, 51, 255));
        jButton92.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton92.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton92.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton92);
        jButton92.setBounds(70, 390, 40, 40);

        jButton93.setBackground(new java.awt.Color(51, 51, 255));
        jButton93.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton93.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton93.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton93);
        jButton93.setBounds(110, 390, 40, 40);

        jButton94.setBackground(new java.awt.Color(51, 51, 255));
        jButton94.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton94.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton94.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton94);
        jButton94.setBounds(150, 390, 40, 40);

        jButton95.setBackground(new java.awt.Color(51, 51, 255));
        jButton95.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton95.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton95.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton95);
        jButton95.setBounds(190, 390, 40, 40);

        jButton96.setBackground(new java.awt.Color(51, 51, 255));
        jButton96.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton96.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton96.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton96);
        jButton96.setBounds(230, 390, 40, 40);

        jButton97.setBackground(new java.awt.Color(51, 51, 255));
        jButton97.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton97.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton97.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton97);
        jButton97.setBounds(270, 390, 40, 40);

        jButton98.setBackground(new java.awt.Color(51, 51, 255));
        jButton98.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton98.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton98.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton98);
        jButton98.setBounds(310, 390, 40, 40);

        jButton99.setBackground(new java.awt.Color(51, 51, 255));
        jButton99.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton99.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton99.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton99);
        jButton99.setBounds(350, 390, 40, 40);

        jButton100.setBackground(new java.awt.Color(51, 51, 255));
        jButton100.setMaximumSize(new java.awt.Dimension(30, 40));
        jButton100.setMinimumSize(new java.awt.Dimension(30, 40));
        jButton100.setPreferredSize(new java.awt.Dimension(30, 40));
        add(jButton100);
        jButton100.setBounds(390, 390, 40, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
